---
name: Deployment
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
        default: "dev"
      clean:
        type: boolean
        required: true
        default: false
      excludeSubfolder:
        type: string
        required: false
        default: ""
      index-mode:
        type: string
        required: true
        default: "index"
      NODE_OPTIONS:
        type: string
        required: false
        default: ""
      DESKTOP_SCREEN_WIDTH:
        type: string
        required: false
        default: ""
      DESKTOP_FOOTER_SCREEN_WIDTH_MAX:
        type: string
        required: false
        default: ""
      PRODUCT_NAME:
        type: string
        required: false
        default: ""
      TEMPLATE_ID_DEV:
        type: string
        required: false
        default: ""
      TEMPLATE_ID_PROD:
        type: string
        required: false
        default: ""
      DC_LINKED_IN:
        type: string
        required: false
        default: ""
      CPU_COUNT:
        type: string
        required: false
        default: "2"

jobs:
  set-state:
    runs-on: ubuntu-latest
    outputs:
      deploy_prod: ${{ contains(inputs.env, 'prod') }}
      deploy_dev: ${{ contains(inputs.env, 'dev') }}
      clean_cache: ${{ inputs.clean }}
      path_prefix: ${{ steps.get_path_prefix.outputs.path_prefix }}
      branch_short_ref: ${{ steps.get_branch.outputs.branch }}
      exclude_subfolder: ${{ inputs.excludeSubfolder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: AdobeDocs/adp-devsite-scripts
          path: scripts
          ref: main

      - name: Get path prefix
        uses: actions/github-script@v7
        id: get_path_prefix
        with:
          script: |
            const script = require('./scripts/gatsby-get-path-prefix.js');
            script({ core });
          result-encoding: string

      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
        id: get_branch

      - name: Delete unused cached tools
        run: |
          sudo rm -rf /opt/hostedtoolcache/Python
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/hostedtoolcache/go
          sudo rm -rf /opt/hostedtoolcache/Ruby
          sudo rm -rf /opt/hostedtoolcache/PyPy

  echo-state:
    needs: [set-state]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to dev - ${{ needs.set-state.outputs.deploy_dev }}"
      - run: echo "Deploy to prod - ${{ needs.set-state.outputs.deploy_prod }}"
      - run: echo "Clean cache - ${{ needs.set-state.outputs.clean_cache }}"
      - run: echo "Repository org - ${{ github.event.repository.owner.login }}"
      - run: echo "Repository name - ${{ github.event.repository.name }}"
      - run: echo "Repository branch - ${{ needs.set-state.outputs.branch_short_ref }}"
      - run: echo "Path prefix - ${{ needs.set-state.outputs.path_prefix }}"
      - run: echo "Exclude subfolder - ${{ needs.set-state.outputs.exclude_subfolder }}"

  pre-build-dev:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.deploy_dev == 'true'
    steps:
      - name: check dev azure connection string
        if: env.AIO_AZURE_DEV_CONNECTION_STRING == null
        run: |
          echo "::error::Please set the Azure Blob Storage connection string as AIO_AZURE_DEV_CONNECTION_STRING in Github Secrets"
          exit 1
        env:
          AIO_AZURE_DEV_CONNECTION_STRING: ${{ secrets.AIO_AZURE_DEV_CONNECTION_STRING }}

  build-dev:
    defaults:
      run:
        shell: bash
    needs: [set-state, pre-build-dev]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node v20 for Yarn v3
        uses: actions/setup-node@v3
        with:
          node-version: "20.19.5" # Current LTS version

      - name: Enable Corepack for Yarn v3
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: Gatsby Cache
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ needs.set-state.outputs.branch_short_ref }}-gatsby-cache-${{ github.run_id }}
          restore-keys: |
            ${{ needs.set-state.outputs.branch_short_ref }}-gatsby-cache-

      - name: Clean Cache
        if: needs.set-state.outputs.clean_cache == 'true'
        run: yarn clean

      - name: Build site
        run: yarn build
        env:
          PREFIX_PATHS: true # equivalent to --prefix-paths flag for 'gatsby build'
          PATH_PREFIX: ${{ needs.set-state.outputs.path_prefix }}
          GATSBY_ADOBE_LAUNCH_SRC: ${{ secrets.AIO_ADOBE_LAUNCH_DEV_SRC }}
          GATSBY_ADDITIONAL_ADOBE_ANALYTICS_ACCOUNTS: ${{ secrets.AIO_REPORT_SUITE_DEV}}
          GATSBY_ADOBE_ANALYTICS_ENV: "dev"
          REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_BRANCH: ${{ needs.set-state.outputs.branch_short_ref }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_DOCS_TOKEN: ${{ secrets.GOOGLE_DOCS_TOKEN }}
          GOOGLE_DOCS_FOLDER_ID: ${{ secrets.GOOGLE_DOCS_FOLDER_ID }}
          GATSBY_IMS_SRC: ${{ secrets.AIO_IMS_DEV_SRC }}
          GATSBY_IMS_CONFIG: ${{ secrets.AIO_IMS_DEV_CONFIG }}
          GATSBY_ALGOLIA_APPLICATION_ID: ${{ secrets.AIO_ALGOLIA_APPLICATION_ID }}
          GATSBY_ALGOLIA_SEARCH_API_KEY: ${{ secrets.AIO_ALGOLIA_SEARCH_API_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.AIO_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_API_KEY: ${{ secrets.AIO_ALGOLIA_API_KEY }}
          GATSBY_ALGOLIA_INDEX_ALL_SRC: ${{ secrets.AIO_ALGOLIA_INDEX_ALL_SRC }}
          GATSBY_ALGOLIA_SEARCH_INDEX: ${{ secrets.AIO_ALGOLIA_SEARCH_INDEX }}
          GATSBY_ALGOLIA_INDEX_ENV_PREFIX: ${{ secrets.AIO_ALGOLIA_INDEX_ENV_PREFIX }}
          GATSBY_FEDS_PRIVACY_ID: ${{ secrets.AIO_FEDS_PRIVACY_ID }}
          GATSBY_SITE_DOMAIN_URL: https://developer-stage.adobe.com
          GATSBY_REDOCLY_KEY: ${{ secrets.REDOCLY_LICENSE_KEY }}
          GATSBY_DESKTOP_SCREEN_WIDTH: ${{ inputs.DESKTOP_SCREEN_WIDTH }}
          GATSBY_DESKTOP_FOOTER_SCREEN_WIDTH_MAX: ${{ inputs.DESKTOP_FOOTER_SCREEN_WIDTH_MAX }}
          GATSBY_PRODUCT_NAME: ${{ inputs.PRODUCT_NAME }}
          GATSBY_TEMPLATE_ID: ${{ inputs.TEMPLATE_ID_DEV }}
          GATSBY_DC_LINKED_IN: ${{ inputs.DC_LINKED_IN }}
          NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
          CPU_COUNT: ${{ inputs.CPU_COUNT }}

      - name: Deploy
        uses: AdobeDocs/static-website-deploy@master
        with:
          enabled-static-website: "true"
          source: "public"
          target: ${{ needs.set-state.outputs.path_prefix }}
          connection-string: ${{ secrets.AIO_AZURE_DEV_CONNECTION_STRING }}
          remove-existing-files: "true"
          exclude-subfolder: ${{ needs.set-state.outputs.exclude_subfolder }}
      - name: Purge Fastly Cache
        uses: AdobeDocs/gatsby-fastly-purge-action@master
        with:
          fastly-token: ${{ secrets.AIO_FASTLY_TOKEN }}
          fastly-url: "${{ secrets.AIO_FASTLY_DEV_URL}}${{ needs.set-state.outputs.path_prefix }}"

  pre-build-production:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.deploy_prod == 'true'
    steps:
      - name: check prod azure connection string
        if: env.AIO_AZURE_PROD_CONNECTION_STRING == null
        run: |
          echo "::error::Please set the Azure Blob Storage connection string as AIO_AZURE_PROD_CONNECTION_STRING in Github Secrets"
          exit 1
        env:
          AIO_AZURE_PROD_CONNECTION_STRING: ${{ secrets.AIO_AZURE_PROD_CONNECTION_STRING }}

  build-production:
    defaults:
      run:
        shell: bash
    needs: [set-state, pre-build-production]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node v20 for Yarn v3
        uses: actions/setup-node@v3
        with:
          node-version: "20.19.5" # Current LTS version

      - name: Enable Corepack for Yarn v3
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: Gatsby Cache
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ needs.set-state.outputs.branch_short_ref }}-gatsby-cache-${{ github.run_id }}
          restore-keys: |
            ${{ needs.set-state.outputs.branch_short_ref }}-gatsby-cache-

      - name: Clean Cache
        if: needs.set-state.outputs.clean_cache == 'true'
        run: yarn clean

      - name: Build site
        run: yarn build
        env:
          PREFIX_PATHS: true # equivalent to --prefix-paths flag for 'gatsby build'
          PATH_PREFIX: ${{ needs.set-state.outputs.path_prefix }}
          GATSBY_ADOBE_LAUNCH_SRC: ${{ secrets.AIO_ADOBE_LAUNCH_PROD_SRC }}
          GATSBY_ADDITIONAL_ADOBE_ANALYTICS_ACCOUNTS: ${{ secrets.AIO_REPORT_SUITE_PROD }}
          GATSBY_ADOBE_ANALYTICS_ENV: "production"
          REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_BRANCH: ${{ needs.set-state.outputs.branch_short_ref }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_DOCS_TOKEN: ${{ secrets.GOOGLE_DOCS_TOKEN }}
          GOOGLE_DOCS_FOLDER_ID: ${{ secrets.GOOGLE_DOCS_FOLDER_ID }}
          GATSBY_IMS_SRC: ${{ secrets.AIO_IMS_PROD_SRC }}
          GATSBY_IMS_CONFIG: ${{ secrets.AIO_IMS_PROD_CONFIG }}
          GATSBY_ALGOLIA_APPLICATION_ID: ${{ secrets.AIO_ALGOLIA_APPLICATION_ID }}
          GATSBY_ALGOLIA_SEARCH_API_KEY: ${{ secrets.AIO_ALGOLIA_SEARCH_API_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.AIO_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_API_KEY: ${{ secrets.AIO_ALGOLIA_API_KEY }}
          ALGOLIA_WRITE_API_KEY: ${{ secrets.AIO_ALGOLIA_WRITE_API_KEY }}
          ALGOLIA_INDEXATION_MODE: ${{ inputs.index-mode || 'index' }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME || github.event.repository.name }}
          GATSBY_ALGOLIA_INDEX_ALL_SRC: ${{ secrets.AIO_ALGOLIA_INDEX_ALL_SRC }}
          GATSBY_ALGOLIA_SEARCH_INDEX: ${{ secrets.AIO_ALGOLIA_SEARCH_INDEX }}
          GATSBY_ALGOLIA_INDEX_ENV_PREFIX: ${{ secrets.AIO_ALGOLIA_INDEX_ENV_PREFIX }}
          GATSBY_FEDS_PRIVACY_ID: ${{ secrets.AIO_FEDS_PRIVACY_ID }}
          GATSBY_SITE_DOMAIN_URL: https://developer.adobe.com
          GATSBY_REDOCLY_KEY: ${{ secrets.REDOCLY_LICENSE_KEY }}
          GATSBY_DESKTOP_SCREEN_WIDTH: ${{ inputs.DESKTOP_SCREEN_WIDTH }}
          GATSBY_DESKTOP_FOOTER_SCREEN_WIDTH_MAX: ${{ inputs.DESKTOP_FOOTER_SCREEN_WIDTH_MAX }}
          GATSBY_PRODUCT_NAME: ${{ inputs.PRODUCT_NAME }}
          GATSBY_TEMPLATE_ID: ${{ inputs.TEMPLATE_ID_PROD }}
          GATSBY_DC_LINKED_IN: ${{ inputs.DC_LINKED_IN }}
          NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
          CPU_COUNT: ${{ inputs.CPU_COUNT }}
      - name: Deploy
        uses: AdobeDocs/static-website-deploy@master
        with:
          enabled-static-website: "true"
          source: "public"
          target: ${{ needs.set-state.outputs.path_prefix }}
          connection-string: ${{ secrets.AIO_AZURE_PROD_CONNECTION_STRING }}
          remove-existing-files: "true"
          exclude-subfolder: ${{ needs.set-state.outputs.exclude_subfolder }}

      - name: Purge Fastly Cache
        uses: AdobeDocs/gatsby-fastly-purge-action@master
        with:
          fastly-token: ${{ secrets.AIO_FASTLY_TOKEN }}
          fastly-url: "${{ secrets.AIO_FASTLY_PROD_URL }}${{ needs.set-state.outputs.path_prefix }}"